package com.xaniihub.app.localization

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import java.util.Locale
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class AppLanguage(val code: String, val title: String) {
    RU("ru", "Русский"),
    EN("en", "English")
}

object AppLanguageController {
    private const val PREFS = "ringwalk_language"
    private const val KEY_LANGUAGE = "language"
    private const val KEY_CONFIGURED = "configured"
    private const val KEY_CREATOR_INFO_SEEN = "creator_info_seen"
    private const val KEY_ONBOARDED = "onboarded"

    var language by mutableStateOf(AppLanguage.RU)
        private set
    private val _languageFlow = MutableStateFlow(language)
    val languageFlow = _languageFlow.asStateFlow()
    var configured by mutableStateOf(false)
        private set
    var creatorInfoSeen by mutableStateOf(false)
        private set
    var onboarded by mutableStateOf(false)
        private set

    fun init(context: Context) {
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        val code = prefs.getString(KEY_LANGUAGE, AppLanguage.RU.code) ?: AppLanguage.RU.code
        updateLanguage(AppLanguage.values().firstOrNull { it.code == code } ?: AppLanguage.RU)
        configured = prefs.getBoolean(KEY_CONFIGURED, false)
        creatorInfoSeen = prefs.getBoolean(KEY_CREATOR_INFO_SEEN, false)
        onboarded = prefs.getBoolean(KEY_ONBOARDED, false)
    }

    fun setLanguage(context: Context, value: AppLanguage, markConfigured: Boolean = true) {
        updateLanguage(value)
        configured = configured || markConfigured
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putString(KEY_LANGUAGE, value.code)
            .putBoolean(KEY_CONFIGURED, configured)
            .commit()
        // Widget captions are localised through appString – repaint them in the new language.
        com.xaniihub.app.widget.RingWalkWidgets.refreshAllAsync(context)
    }

    private fun updateLanguage(value: AppLanguage) {
        language = value
        _languageFlow.value = value
    }

    fun markOnboarded(context: Context) {
        onboarded = true
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putBoolean(KEY_ONBOARDED, true)
            .apply()
    }

    fun markCreatorInfoSeen(context: Context) {
        creatorInfoSeen = true
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putBoolean(KEY_CREATOR_INFO_SEEN, true)
            .apply()
    }
}

@androidx.compose.runtime.Composable
fun appText(key: String): String = appString(key)

fun appString(key: String): String {
    val lang = AppLanguageController.language
    return when (lang) {
        AppLanguage.RU -> ru[key]
        AppLanguage.EN -> en[key]
    } ?: ru[key] ?: key
}

fun appLocale(language: AppLanguage = AppLanguageController.language): Locale = when (language) {
    AppLanguage.RU -> Locale("ru", "RU")
    AppLanguage.EN -> Locale.US
}

private val ru = mapOf(
    "challenges_title" to "Челленджи",
    "challenges_subtitle" to "Создавайте свои челленджи и следите за прогрессом",
    "new_challenge" to "Новый челлендж",
    "challenge_name" to "Название челленджа",
    "metric_label" to "Метрика",
    "metric_steps" to "Шаги",
    "metric_calories" to "Калории",
    "metric_distance" to "Дистанция",
    "target_steps" to "Цель в шагах",
    "target_calories" to "Цель в ккал",
    "target_distance" to "Цель в км",
    "duration_days" to "Дней",
    "create_challenge" to "Создать челлендж",
    "active_challenges" to "Активные челленджи",
    "no_challenges" to "Пока нет челленджей. Создайте первый выше.",
    "days_left" to "дн. осталось",
    "challenge_completed" to "Выполнено 🎉",
    "challenge_failed" to "Время вышло",
    "challenge_archive" to "Архив челленджей",
    "delete" to "Удалить",
    "delete_challenge_title" to "Удалить челлендж?",
    "delete_challenge_message" to "Это действие нельзя отменить.",
    "confirm_delete" to "Удалить",
    "default_steps_challenge" to "Челлендж по шагам",
    "default_calories_challenge" to "Челлендж по калориям",
    "default_distance_challenge" to "Челлендж по дистанции",
    "input_error" to "Введите корректное значение в допустимом диапазоне",
    "choose_language" to "Выберите язык",
    "choose_language_subtitle" to "Язык можно изменить позже внизу профиля.",
    "statistics" to "Статистика",
    "stats_subtitle" to "День / Неделя / Месяц / Год",
    "day" to "День",
    "body_parameters" to "Параметры тела",
    "other" to "Другое",
    "kcal_per_day" to "ккал / день",
    "burned_today" to "ккал сегодня",
    "burned" to "Сожжено",
    "russian" to "Русский",
    "language" to "Язык",
    "language_subtitle" to "Переключение языка интерфейса",
    "home" to "Главная",
    "analytics" to "Аналитика",
    "goals" to "Цели",
    "achievements" to "Достижения",
    "profile" to "Профиль",
    "permission" to "Для работы шагомера нужно разрешение на физическую активность. Уведомления можно не разрешать.",
    "permission_settings" to "Разрешение на физическую активность отключено. Разрешите его в настройках приложения.",
    "allow" to "Разрешить",
    "open_settings" to "Открыть настройки",
    "step_sensor_unavailable" to "На этом устройстве нет датчика шагов. RingWalk не сможет автоматически считать шаги.",
    "creator_title" to "О создателе",
    "creator_name" to "Создатель: Xanii",
    "creator_age" to "Мне 14 лет",
    "creator_story" to "Я разработал RingWalk, чтобы люди не платили за базовые вещи вроде шагомера. Простые и полезные функции должны быть доступны каждому.",
    "start_app" to "Начать пользоваться",
    "today" to "Сегодня",
    "selected_day" to "Выбранный день",
    "calendar" to "Календарь",
    "previous_day" to "Предыдущий день",
    "next_day" to "Следующий день",
    "activity_today" to "Активность сегодня",
    "activity_archive" to "Архив активности",
    "of_steps" to "из %s шагов",
    "distance" to "Дистанция",
    "calories" to "Калории",
    "time" to "Время",
    "hourly_activity" to "Почасовая активность",
    "hourly_peak" to "Максимум за час: %s шагов",
    "weight_trend_empty" to "Добавьте первый вес, чтобы увидеть динамику.",
    "streak_days" to "Серия без пропусков: %s дней",
    "streak_short" to "Серия: %s дн.",
    "daily_goal" to "Дневная цель",
    "steps_value" to "%s шагов",
    "lifetime_steps" to "Шагов за всё время",
    "change" to "Изменить",
    "select" to "Выбрать",
    "cancel" to "Отмена",
    "save" to "Сохранить",
    "steps_per_day" to "Шагов в день",
    "km" to "км",
    "min" to "мин",
    "hour_short" to "ч",
    "kcal" to "ккал",
    "goals_subtitle" to "Управляйте дневными, недельными и месячными целями",
    "goal_day" to "Цель на день",
    "goal_week" to "Цель на неделю",
    "goal_month" to "Цель на месяц",
    "save_goals" to "Сохранить цели",
    "save_goal_type" to "Сохранить эту цель",
    "achievements_subtitle" to "Награды, уровни, streak и мини-челленджи",
    "received" to "Получено",
    "threshold" to "Порог %s",
    "mini_challenges" to "Мини-челленджи",
    "morning_boost" to "Утренний разгон",
    "morning_boost_desc" to "Пройти 3 000 шагов до 12:00",
    "evening_streak" to "Серия на два дня",
    "evening_streak_desc" to "Пройти суммарно 16 000 шагов за вчера и сегодня",
    "weekly_sprint" to "Спринт недели",
    "weekly_sprint_desc" to "Набрать 50 000 шагов с понедельника",
    "year_steps" to "Шагов за год",
    "average_day" to "Среднее в день",
    "best_day" to "Самый активный день",
    "chart_day" to "Сегодня",
    "chart_week" to "Последние 7 дней",
    "chart_month" to "Последние 30 дней",
    "chart_year" to "Последний год (по месяцам)",
    "no_hourly_data" to "Пока нет почасовых данных за этот день",
    "weekday_letters" to "Пн,Вт,Ср,Чт,Пт,Сб,Вс",
    "comparison" to "Сравнение",
    "prev_month" to "К прошлому месяцу: %s%%",
    "year_forecast" to "Прогноз на год: %s",
    "activity_heatmap" to "Heatmap активности",
    "profile_subtitle" to "Параметры тела, статистика шагов и персональный расчет калорий",
    "weight_kg" to "Вес (кг)",
    "height_cm" to "Рост (см)",
    "age" to "Возраст",
    "activity_coeff" to "Коэф. активности (1.2 - 1.9)",
    "target_weight" to "Целевой вес (кг)",
    "male" to "М",
    "female" to "Ж",
    "save_params" to "Сохранить параметры",
    "metrics" to "Показатели",
    "weight_dynamics" to "Динамика веса",
    "new_weight" to "Новый вес (кг)",
    "add_weight" to "Добавить вес",
    "create_backup" to "Создать резервную копию",
    "backup_error" to "Ошибка backup: %s",
    "themes" to "Темы",
    "themes_subtitle" to "Выберите цветовую гамму интерфейса",
    "my_day" to "Мой день",
    "steps_metric" to "Шаги",
    "today_caps" to "СЕГОДНЯ",
    "usual_caps" to "ОБЫЧНО",
    "dynamic" to "Динамика",
    "week" to "Неделя",
    "month" to "Месяц",
    "year" to "Год",
    "average" to "Среднее",
    "previous_period" to "Прошлый период",
    "current_period" to "Текущий период",
    "now" to "Сейчас",
    "calories_caps" to "КАЛОРИИ",
    "distance_caps" to "ДИСТАНЦИЯ",
    "duration_caps" to "ПРОДОЛЖИТЕЛЬНОСТЬ",
    "my_day_no_data" to "Как только появятся данные за несколько дней, здесь будет сравнение с обычным уровнем активности.",
    "my_day_more" to "Сегодня вы сделали на %s шагов больше, чем обычно.",
    "my_day_equal" to "Сегодня вы идёте в обычном темпе.",
    "my_day_less" to "Пока что вы сделали меньше шагов, чем обычно. Не хватает %s шагов.",
    "dyn_no_compare" to "Вы прошли в среднем %s шагов в день. Данных для сравнения с прошлым периодом пока мало.",
    "dyn_more" to "Вы прошли в среднем %s шагов в день. Это на %s больше, чем за предыдущий период.",
    "dyn_less" to "Вы прошли в среднем %s шагов в день. Это на %s меньше, чем за предыдущий период.",
    "underweight" to "Недостаточный вес",
    "normal" to "Норма",
    "overweight" to "Избыточный вес",
    "obesity" to "Ожирение",
    "goal_types_title" to "Цели по типам",
    "goal_types_subtitle" to "Включайте нужные метрики и задавайте дневные цели.",
    "goal_type_steps" to "Шаги",
    "goal_type_calories" to "Калории",
    "goal_type_distance" to "Дистанция",
    "goal_type_active" to "Активные минуты",
    "goal_target_label" to "Цель",
    "unit_kcal" to "ккал",
    "unit_km" to "км",
    "unit_min" to "мин",
    "unit_steps" to "шагов",
    "onb_welcome_title" to "Добро пожаловать в RingWalk",
    "onb_welcome_text" to "Ваш ежедневный спутник для шагов, активности и целей.",
    "onb_track_title" to "Отслеживайте всё",
    "onb_track_text" to "Шаги, калории, дистанция и активные минуты — в одном кольце.",
    "onb_goal_title" to "Выберите дневную цель",
    "onb_goal_text" to "Сколько шагов вы хотите проходить каждый день?",
    "onb_ready_title" to "Всё готово!",
    "onb_ready_text" to "Добавьте виджет на экран или плитку в шторку для быстрого доступа.",
    "onb_next" to "Далее",
    "onb_back" to "Назад",
    "onb_start" to "Начать",
    "onb_skip" to "Пропустить",
    "onb_profile_title" to "Расскажите о себе",
    "onb_profile_text" to "Это нужно для точного расчёта калорий и активности.",
    "onb_gender" to "Пол",
    "onb_gender_male" to "Мужской",
    "onb_gender_female" to "Женский",
    "onb_gender_other" to "Другой",
    "onb_age" to "Возраст",
    "onb_height" to "Рост",
    "onb_weight" to "Вес",
    "onb_activity_title" to "Уровень активности",
    "onb_activity_text" to "Влияет на дневную норму калорий (коэффициент).",
    "act_sedentary" to "Сидячий образ жизни",
    "act_light" to "Лёгкая активность",
    "act_moderate" to "Умеренная активность",
    "act_active" to "Высокая активность",
    "act_very" to "Очень высокая",
    "unit_kg" to "кг",
    "unit_cm" to "см",
    "unit_years" to "лет",
    "tracking_notification_title" to "RingWalk работает в фоне",
    "tracking_notification_channel" to "Отслеживание RingWalk",
    "inactivity_notification_channel" to "Напоминания RingWalk",
    "inactivity_notification_text" to "Вы давно не двигались. Небольшая прогулка поможет закрыть цель.",
    "notification_distance_m" to "м",
    "achievement_10k" to "Старт 10k",
    "achievement_100k" to "Покоритель 100k",
    "achievement_1m" to "Легенда миллиона",
    "achievement_description" to "Достигните %s шагов за всё время",
    "widget_goal" to "Цель %s",
    "widget_title" to "Шаги сегодня",
    "widget_remaining" to "Осталось %s",
    "widget_goal_reached" to "Цель достигнута ✓",
    "widget_streak_label" to "серия",
    "widget_week_total" to "%s за неделю",
    "widget_week_avg" to "В среднем %s в день"
)

private val en = mapOf(
    "challenges_title" to "Challenges",
    "challenges_subtitle" to "Create your own challenges and track progress",
    "new_challenge" to "New challenge",
    "challenge_name" to "Challenge name",
    "metric_label" to "Metric",
    "metric_steps" to "Steps",
    "metric_calories" to "Calories",
    "metric_distance" to "Distance",
    "target_steps" to "Target steps",
    "target_calories" to "Target kcal",
    "target_distance" to "Target km",
    "duration_days" to "Days",
    "create_challenge" to "Create challenge",
    "active_challenges" to "Active challenges",
    "no_challenges" to "No challenges yet. Create your first one above.",
    "days_left" to "days left",
    "challenge_completed" to "Completed 🎉",
    "challenge_failed" to "Time is up",
    "challenge_archive" to "Challenge archive",
    "delete" to "Delete",
    "delete_challenge_title" to "Delete challenge?",
    "delete_challenge_message" to "This action cannot be undone.",
    "confirm_delete" to "Delete",
    "default_steps_challenge" to "Steps challenge",
    "default_calories_challenge" to "Calories challenge",
    "default_distance_challenge" to "Distance challenge",
    "input_error" to "Enter a valid value within the allowed range",
    "choose_language" to "Choose language",
    "choose_language_subtitle" to "You can change it later at the bottom of Profile.",
    "statistics" to "Statistics",
    "stats_subtitle" to "Day / Week / Month / Year",
    "day" to "Day",
    "body_parameters" to "Body parameters",
    "other" to "Other",
    "kcal_per_day" to "kcal / day",
    "burned_today" to "today kcal",
    "burned" to "Burned",
    "russian" to "Русский",
    "language" to "Language",
    "language_subtitle" to "Interface language switcher",
    "home" to "Home",
    "analytics" to "Analytics",
    "goals" to "Goals",
    "achievements" to "Awards",
    "profile" to "Profile",
    "permission" to "The pedometer needs physical-activity permission. Notifications are optional.",
    "permission_settings" to "Physical-activity permission is disabled. Allow it in the app settings.",
    "allow" to "Allow",
    "open_settings" to "Open settings",
    "step_sensor_unavailable" to "This device has no step sensor. RingWalk cannot count steps automatically.",
    "creator_title" to "About the creator",
    "creator_name" to "Creator: Xanii",
    "creator_age" to "I am 14 years old",
    "creator_story" to "I developed RingWalk so people do not have to pay for basic things like a pedometer. Simple and useful features should be available to everyone.",
    "start_app" to "Start using RingWalk",
    "today" to "Today",
    "selected_day" to "Selected day",
    "calendar" to "Calendar",
    "previous_day" to "Previous day",
    "next_day" to "Next day",
    "activity_today" to "Today's activity",
    "activity_archive" to "Activity archive",
    "of_steps" to "of %s steps",
    "distance" to "Distance",
    "calories" to "Calories",
    "time" to "Time",
    "hourly_activity" to "Hourly activity",
    "hourly_peak" to "Peak hour: %s steps",
    "weight_trend_empty" to "Add your first weight to see its trend.",
    "streak_days" to "Streak without skips: %s days",
    "streak_short" to "%s-day streak",
    "daily_goal" to "Daily goal",
    "steps_value" to "%s steps",
    "lifetime_steps" to "Lifetime steps",
    "change" to "Change",
    "select" to "Select",
    "cancel" to "Cancel",
    "save" to "Save",
    "steps_per_day" to "Steps per day",
    "km" to "km",
    "min" to "min",
    "hour_short" to "h",
    "kcal" to "kcal",
    "goals_subtitle" to "Manage daily, weekly and monthly goals",
    "goal_day" to "Daily goal",
    "goal_week" to "Weekly goal",
    "goal_month" to "Monthly goal",
    "save_goals" to "Save goals",
    "save_goal_type" to "Save this goal",
    "achievements_subtitle" to "Awards, levels, streaks and mini-challenges",
    "received" to "Unlocked",
    "threshold" to "Target %s",
    "mini_challenges" to "Mini-challenges",
    "morning_boost" to "Morning boost",
    "morning_boost_desc" to "Walk 3,000 steps before 12:00",
    "evening_streak" to "Two-day streak",
    "evening_streak_desc" to "Walk 16,000 total steps yesterday and today",
    "weekly_sprint" to "Weekly sprint",
    "weekly_sprint_desc" to "Reach 50,000 steps from Monday",
    "year_steps" to "Steps this year",
    "average_day" to "Daily average",
    "best_day" to "Most active day",
    "chart_day" to "Today",
    "chart_week" to "Last 7 days",
    "chart_month" to "Last 30 days",
    "chart_year" to "Last year (by month)",
    "no_hourly_data" to "No hourly data for this day yet",
    "weekday_letters" to "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    "comparison" to "Comparison",
    "prev_month" to "Vs last month: %s%%",
    "year_forecast" to "Year forecast: %s",
    "activity_heatmap" to "Activity heatmap",
    "profile_subtitle" to "Body parameters, step stats and personal calorie calculation",
    "weight_kg" to "Weight (kg)",
    "height_cm" to "Height (cm)",
    "age" to "Age",
    "activity_coeff" to "Activity coefficient (1.2 - 1.9)",
    "target_weight" to "Target weight (kg)",
    "male" to "M",
    "female" to "F",
    "save_params" to "Save parameters",
    "metrics" to "Metrics",
    "weight_dynamics" to "Weight dynamics",
    "new_weight" to "New weight (kg)",
    "add_weight" to "Add weight",
    "create_backup" to "Create backup",
    "backup_error" to "Backup error: %s",
    "themes" to "Themes",
    "themes_subtitle" to "Choose interface color palette",
    "my_day" to "My day",
    "steps_metric" to "Steps",
    "today_caps" to "TODAY",
    "usual_caps" to "USUAL",
    "dynamic" to "Dynamics",
    "week" to "Week",
    "month" to "Month",
    "year" to "Year",
    "average" to "Average",
    "previous_period" to "Previous period",
    "current_period" to "Current period",
    "now" to "Now",
    "calories_caps" to "CALORIES",
    "distance_caps" to "DISTANCE",
    "duration_caps" to "DURATION",
    "my_day_no_data" to "Once there is data for several days, you will see a comparison with your usual activity level here.",
    "my_day_more" to "Today you walked %s steps more than usual.",
    "my_day_equal" to "Today you are moving at your usual pace.",
    "my_day_less" to "You have fewer steps than usual so far. %s steps left.",
    "dyn_no_compare" to "You walked an average of %s steps per day. There is not enough data to compare with the previous period yet.",
    "dyn_more" to "You walked an average of %s steps per day. That is %s more than in the previous period.",
    "dyn_less" to "You walked an average of %s steps per day. That is %s less than in the previous period.",
    "underweight" to "Underweight",
    "normal" to "Normal",
    "overweight" to "Overweight",
    "obesity" to "Obesity",
    "goal_types_title" to "Goals by type",
    "goal_types_subtitle" to "Enable the metrics you care about and set daily targets.",
    "goal_type_steps" to "Steps",
    "goal_type_calories" to "Calories",
    "goal_type_distance" to "Distance",
    "goal_type_active" to "Active minutes",
    "goal_target_label" to "Target",
    "unit_kcal" to "kcal",
    "unit_km" to "km",
    "unit_min" to "min",
    "unit_steps" to "steps",
    "onb_welcome_title" to "Welcome to RingWalk",
    "onb_welcome_text" to "Your daily companion for steps, activity and goals.",
    "onb_track_title" to "Track everything",
    "onb_track_text" to "Steps, calories, distance and active minutes in one ring.",
    "onb_goal_title" to "Pick your daily goal",
    "onb_goal_text" to "How many steps do you want to walk every day?",
    "onb_ready_title" to "You are all set!",
    "onb_ready_text" to "Add a home-screen widget or a Quick Settings tile for fast access.",
    "onb_next" to "Next",
    "onb_back" to "Back",
    "onb_start" to "Get started",
    "onb_skip" to "Skip",
    "onb_profile_title" to "Tell us about you",
    "onb_profile_text" to "Used for accurate calories and activity calculations.",
    "onb_gender" to "Gender",
    "onb_gender_male" to "Male",
    "onb_gender_female" to "Female",
    "onb_gender_other" to "Other",
    "onb_age" to "Age",
    "onb_height" to "Height",
    "onb_weight" to "Weight",
    "onb_activity_title" to "Activity level",
    "onb_activity_text" to "Affects your daily calorie target (multiplier).",
    "act_sedentary" to "Sedentary",
    "act_light" to "Lightly active",
    "act_moderate" to "Moderately active",
    "act_active" to "Very active",
    "act_very" to "Extra active",
    "unit_kg" to "kg",
    "unit_cm" to "cm",
    "unit_years" to "yrs",
    "tracking_notification_title" to "RingWalk is running in background",
    "tracking_notification_channel" to "RingWalk tracking",
    "inactivity_notification_channel" to "RingWalk reminders",
    "inactivity_notification_text" to "You have not moved for a while. A short walk can help close your goal.",
    "notification_distance_m" to "m",
    "achievement_10k" to "10k Starter",
    "achievement_100k" to "100k Walker",
    "achievement_1m" to "Million Legend",
    "achievement_description" to "Reach %s lifetime steps",
    "widget_goal" to "Goal %s",
    "widget_title" to "Steps today",
    "widget_remaining" to "%s to go",
    "widget_goal_reached" to "Goal reached ✓",
    "widget_streak_label" to "streak",
    "widget_week_total" to "%s this week",
    "widget_week_avg" to "Avg %s a day"
)